// designs/default/react-v18/src/components/Badge.tsx
import { forwardRef } from "react";
import type { HTMLAttributes } from "react";
import type { BadgeContract, ComponentSize } from "@design-system/contracts";
import clsx from "clsx";
import "../design-system/components/badge.css";

export interface BadgeProps
  extends HTMLAttributes<HTMLDivElement>,
    BadgeContract {
  size?: ComponentSize;
}

export const Badge = forwardRef<HTMLDivElement, BadgeProps>(function Badge(
  { variant = "solid", tone = "neutral", size = "md", className, ...rest },
  ref
) {
  return (
    <div
      ref={ref}
      className={clsx(
        "badge",
        `badge--${variant}`,
        `badge--${tone}`,
        `badge--${size}`,
        className
      )}
      {...rest}
    />
  );
});

// packages/component-libraries/svelte-v5/src/lib/components/badge/Badge.svelte
<script lang="ts">
  import type { BadgeContract } from "@design-system/contracts";
  import type { Snippet } from "svelte";
  import "./badge.css";

  interface Props extends BadgeContract {
    children?: Snippet | string;
  }

  let {
    variant = "solid",
    tone = "neutral",
    children,
  }: Props = $props();
</script>

<span data-variant={variant} data-tone={tone}>
  {#if typeof children === "string"}
    {children}
  {:else}
    {@render children?.()}
  {/if}
</span>
