// designs/default/react-v18/src/components/Button.tsx
import { forwardRef } from "react";
import type { ButtonHTMLAttributes } from "react";
import type { ButtonContract } from "@design-system/contracts";
import clsx from "clsx";
import "../design-system/components/button.css";

export type ButtonProps = ButtonHTMLAttributes<HTMLButtonElement> & ButtonContract;

export const Button = forwardRef<HTMLButtonElement, ButtonProps>(function Button(
  {
    variant = "primary",
    size = "md",
    loading = false,
    disabled,
    className,
    ...rest
  },
  ref
) {
  return (
    <button
      ref={ref}
      className={clsx("btn", `btn--${variant}`, `btn--${size}`, className)}
      disabled={disabled || loading}
      aria-busy={loading || undefined}
      {...rest}
    />
  );
});

// designs/default/svelte-v5/src/lib/components/button/Button.svelte
<script lang="ts">
  import type { ButtonContract } from "@design-system/contracts";
  import type { Snippet } from "svelte";
  import "./button.css";

  interface Props extends ButtonContract {
    children?: Snippet | string;
    onclick?: (e: MouseEvent) => void;
  }

  let {
    variant = "primary",
    size = "md",
    disabled = false,
    loading = false,
    type = "button",
    children,
    onclick,
  }: Props = $props();
</script>

<button
  {type}
  data-variant={variant}
  data-size={size}
  disabled={disabled || loading}
  aria-busy={loading ? "true" : undefined}
  {onclick}
>
  {#if typeof children === "string"}
    {children}
  {:else}
    {@render children?.()}
  {/if}
</button>
